moonbitlang/moon

.github/workflows/ci.yml
.github/workflows/test-on-main.yml

so that core test fail won't block cargo test

CI: move cargo test before core test

---

crates/moon/src/cli/check.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonutil/src/common.rs

`moon check --output-json -q`
close https://github.com/moonbitlang/moon/issues/53
cc @bzy-debug

feat: support moon check output in json format

---

crates/moonbuild/src/upgrade.rs

chore: better upgrade output

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

chore: polish issue templates

---

crates/moon/tests/test_cases/expect_test.in/lib/hello.mbt
crates/moon/tests/test_cases/expect_test.in/lib/hello_wbtest.mbt
crates/moon/tests/test_cases/expect_test.in/lib/issue_188_wbtest.mbt
crates/moon/tests/test_cases/expect_test.in/lib/issue_209.mbt
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/test_filter.in/lib2/lib.mbt

change inspect()! to inspect!()

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/new.rs

chore: add missing file in moon new --lib

---

crates/moonutil/src/render.rs

close https://github.com/moonbitlang/moon/issues/61

fix: render failed should be well handled

---

crates/moonbuild/src/dry_run.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonbuild/src/runtest.rs

follow up https://github.com/moonbitlang/moon/pull/93

internal: don't pre allocate for runnable_artifacts

---

crates/moon/src/cli/check.rs
crates/moonbuild/src/check/watch.rs
crates/moonutil/src/common.rs

related: https://github.com/moonbitlang/moon/issues/52

internal: make moon check --watch more robust

---

crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/runtest.rs
crates/moonutil/src/common.rs

test at [core](https://github.com/moonbitlang/core) with the following result
before: 2.2 seconds on average (after warmup)
after: 0.2 seconds on average (after warmup)
part of https://github.com/moonbitlang/moon/issues/47

feat: parallelize moon test in pkg level

---

crates/moon/src/main.rs
crates/moonbuild/src/check/watch.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/lib.rs
crates/moonbuild/src/upgrade.rs
crates/mooncake/src/lib.rs
crates/mooncake/src/pkg/add.rs
crates/mooncake/src/pkg/install.rs
crates/mooncake/src/pkg/remove.rs
crates/mooncake/src/registry/mock.rs
crates/mooncake/src/registry/online.rs
crates/mooncake/src/resolver/env.rs
crates/mooncake/src/resolver/mvs.rs
crates/moonutil/src/lib.rs

https://rust-lang.github.io/rust-clippy/master/#/clone_on_ref_ptr
cc @Young-Flash

warn clippy::clone_on_ref_ptr

---

crates/moonbuild/src/upgrade.rs

close https://github.com/moonbitlang/moon/issues/105

fix: don't miss mooninfo when upgrade

---

crates/moon/src/cli/shell_completion.rs

To teach user how to use `moon shell-completion`

add discussion section to `moon shell-completion --help`

---

crates/moonbuild/src/dry_run.rs

refact(dry-run): reduce the complexity of bfs_graph to improve performance
- ____

refact(dry-run): reduce the complexity of bfs_graph to improve performance

---

crates/moon/src/cli/generate_test_driver.rs
crates/moonbuild/template/test_driver_template.mbt

internal: tweak test driver

---

crates/moon/src/cli/shell_completion.rs

how to install completions on elvish is missing. now added. Also reminds user to update their completion scripts periodically.

add completion help info for elvish

---

crates/moon/src/cli/generate_test_driver.rs

fix: test driver broken on Windows

---

crates/moon/src/cli/info.rs

- No longer pollute target directory

fix: put mi in respective target directory during info

---

Cargo.lock
Cargo.toml
crates/moonbuild/template/mod.schema.json
crates/moonbuild/template/pkg.schema.json
crates/moonutil/Cargo.toml
crates/moonutil/src/module.rs
crates/moonutil/src/package.rs

close https://github.com/moonbitlang/moon/issues/126

feat: auto generate json schema

---

crates/moon/tests/test_cases/mod.rs

add test cases for `moon version --all`.
- ____

test: add cases for version --all

---

crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs

close https://github.com/moonbitlang/moon/issues/135

fix: don't update test with more than one target

---

crates/moon/src/cli/generate_test_driver.rs
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/specify_source_dir_001.in/moon.test
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonutil/src/common.rs

Seperate gen driver

---

.github/workflows/cd.yml
.github/workflows/ci.yml

also enable test on core in ci

cd: dont upload to aliyun

---

crates/moon/src/cli/test.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/expect.rs
crates/moonbuild/src/runtest.rs
crates/moonutil/src/common.rs

add experimental snapshot testing mechanism

---

crates/moonbuild/src/expect.rs
crates/moonbuild/template/mod_json_schema.html
crates/moonbuild/template/pkg_json_schema.html
crates/moonutil/src/module.rs
crates/moonutil/src/package.rs
docs/manual/src/SUMMARY.md
docs/manual/src/json_schema.md
docs/manual/src/source/mod_json_schema.html
docs/manual/src/source/pkg_json_schema.html
docs/manual/src/tutorial.md
licenserc.toml

related to https://github.com/moonbitlang/moon/issues/124

docs: add json schema viewer

---

crates/moonbuild/src/check/watch.rs

it will trigger `Data(Any)` under windows wsl
close https://github.com/moonbitlang/moon/issues/179

internal: fix watch event not trigger in wsl

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moonutil/src/dirs.rs

this would help https://github.com/moonbitlang/moon/pull/173, making `build` not block `check` trigger by ide

internal: make the lock smaller

---

crates/moon/src/cli/doc.rs

add -std-path flag for moondoc

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/check.rs
crates/moonbuild/src/check/mod.rs
crates/moonbuild/src/lib.rs
crates/moonbuild/src/watch.rs

close https://github.com/moonbitlang/moon/issues/52

feat: support watch mode for build

---

crates/moon/src/cli.rs
crates/moon/src/cli/tool.rs
crates/moon/src/main.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/fmt.rs

part of https://github.com/moonbitlang/moon/issues/180

optimize moon fmt

---

crates/moonbuild/src/entry.rs

clean up unused code to fix warnings on Windows cc @Young-Flash

internal: fix warnings on Windows

---

crates/moonbuild/src/entry.rs

follow up https://github.com/moonbitlang/moon/pull/207

internal: snapshot failure json

---

crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/render.rs

cc https://github.com/moonbitlang/core/pull/927#issuecomment-2311830857

internal: don't repeat diagnostic msg

---

crates/moonbuild/src/expect.rs

ignore differences between LF and CRLF

---

changes.md
crates/moon/src/cli.rs
crates/moon/src/cli/upgrade.rs
crates/moon/src/main.rs
crates/moonbuild/src/upgrade.rs

close https://github.com/moonbitlang/moon/issues/204

feat: check latest version before moon upgrade

---

crates/moon/src/cli/version.rs
crates/moonbuild/src/upgrade.rs
crates/moonutil/src/common.rs
crates/moonutil/src/dirs.rs

close https://github.com/moonbitlang/moon/issues/250 and add error handling for get version (https://github.com/moonbitlang/moon/issues/241)

fix upgrade

---

crates/moonbuild/src/fmt.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_bundle.rs
crates/moonbuild/src/gen/gen_check.rs
crates/moonbuild/src/gen/gen_runtest.rs

related to https://github.com/moonbitlang/moon/issues/244

internal: add error context for n2 db processing

---

Cargo.lock
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/fmt.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_bundle.rs
crates/moonbuild/src/gen/gen_check.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonbuild/src/gen/n2_errors.rs

Related https://github.com/moonbitlang/moon/issues/244

Improve n2 error message

---

crates/moon/tests/test_cases/cond_comp.in/moon.test
crates/moon/tests/test_cases/cond_comp.in/src/lib/moon.pkg.json
crates/moonutil/src/cond_expr.rs

feat: allow empty logic operator

---

crates/moon/src/cli/tool.rs
crates/moon/src/cli/tool/format_and_diff.rs

refactor moon tool

---

.github/PULL_REQUEST_TEMPLATE.md

This trivial patch add a type  `Performance optimization` to the pull request template. Thanks for your review.

Add type of pull request: `Performance optimization`

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs

internal: add package.json for ide test block debug

---

Cargo.lock
crates/moon/Cargo.toml
crates/moon/src/cli.rs
docs/manual-zh/src/SUMMARY.md
docs/manual-zh/src/commands.md
docs/manual/src/SUMMARY.md
docs/manual/src/commands.md

docs: generate help page automatically

---

crates/moon/src/cli.rs
crates/moonutil/src/module.rs
crates/moonutil/src/package.rs
docs/manual-zh/src/SUMMARY.md
docs/manual-zh/src/commands.md
docs/manual-zh/src/json_schema.md
docs/manual-zh/src/source/mod_json_schema.html
docs/manual-zh/src/source/pkg_json_schema.html
docs/manual/src/commands.md

docs(zh): JSON schema

---

crates/moon/tests/test_cases/cond_comp.in/moon.test
crates/moon/tests/test_cases/cond_comp.in/src/lib/moon.pkg.json
docs/manual-zh/src/package/conditional-compilation.md

more condition examples

---

docs/manual-zh/src/package/pre-build.md

docs: update outdated docs

---

crates/moon/src/cli/generate_test_driver.rs
crates/moonbuild/src/entry.rs

don't run test in coverage.mbt in moonbitlang/core/builtin pkg when enable coverage

fix coverage builtin

---

crates/moonbuild/src/entry.rs

internal: check build status after rerun in test mode

---

crates/moon/tests/test_cases/mod.rs

close https://github.com/moonbitlang/moon/issues/339

internal: track interfaces of moonfmt cli

---

crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/test.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonutil/src/common.rs

Improve fuzzy matching

---

crates/moonbuild/template/pkg.schema.json
crates/moonutil/src/package.rs
docs/manual-zh/src/source/pkg_json_schema.html
docs/manual/src/source/pkg_json_schema.html

update json schema for cond compile `target` filed

---

crates/moon/src/cli.rs
crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/pre_build.rs
crates/moon/src/cli/run.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs

need to re-scan the whole module after pre-build

re-scan module after prebuild

---

crates/moonbuild/template/test_driver/no_args_driver_template.mbt
crates/moonbuild/template/test_driver/no_args_driver_template_native.mbt
crates/moonbuild/template/test_driver/wasm_args.mbt
crates/moonbuild/template/test_driver/with_args_driver_template.mbt

cc https://github.com/moonbitlang/core/pull/1084#issue-2577509442

internal: remove Buffer in test driver

---

crates/moon/src/cli.rs
crates/moon/src/cli/mooncake_adapter.rs
crates/moon/src/main.rs
crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/mooncakes.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

only package module but do not publish

feat: add `moon package` subcommand

---

crates/moon/src/cli.rs
crates/moon/tests/test_cases/mod.rs

follow up https://github.com/moonbitlang/moon/pull/384

internal: use "cc -O2 -fwrapv" for native release

---

crates/moonbuild/template/test_driver/js_args.mbt

close https://github.com/moonbitlang/moon/issues/393

internal: update test driver args passing for js backend

---

crates/moon/src/cli/fmt.rs
crates/moon/src/cli/tool.rs
crates/moon/src/cli/tool/format_and_diff.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/fmt.rs
crates/moonutil/src/common.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

Close https://github.com/moonbitlang/moon/issues/407

Moon fmt extra args

---

crates/moonrun/src/main.rs

feat: support --stack-size flag for v8

---

crates/moonutil/src/scan.rs

internal: add error context for src

---

crates/moonbuild/src/entry.rs

Stripping them will interfere with styling if the compiler prints anything other than error messages
Superceeds #426

Don't strip empty lines in main function

---

crates/moonbuild/template/pkg.schema.json
crates/moonrun/src/template/js_glue.js
crates/moonutil/src/package.rs
docs/manual-zh/src/source/pkg_json_schema.html
docs/manual/src/source/pkg_json_schema.html

* update moonrun
* update json schema

update json config

---

crates/moon/src/cli/fmt.rs
crates/moon/src/cli/tool/format_and_diff.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/fmt.rs
crates/moonutil/src/common.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

add `moon fmt --block-style`

---

crates/moon/tests/test_cases/fancy_import.in/import004/main/moon.pkg.json
crates/moonbuild/template/pkg.schema.json
crates/moonutil/src/package.rs
docs/manual-zh/src/source/pkg_json_schema.html
docs/manual/src/source/pkg_json_schema.html

part of https://github.com/moonbitlang/moon/issues/436

allow alias not set when path provided

---

crates/moonbuild/src/watch.rs

close https://github.com/moonbitlang/moon/issues/422

fix watch event kind for windows

---

crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib/hello.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib/hello_test.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib/moon.pkg.json
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib2/hello.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib2/hello_test.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib2/moon.pkg.json
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib3/hello.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib3/hello_test.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/lib3/moon.pkg.json
crates/moon/tests/test_cases/self-pkg-in-test-import.in/main/main.mbt
crates/moon/tests/test_cases/self-pkg-in-test-import.in/main/moon.pkg.json
crates/moon/tests/test_cases/self-pkg-in-test-import.in/moon.mod.json
crates/moonbuild/src/gen/gen_check.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonutil/src/package.rs

part of https://github.com/moonbitlang/moon/issues/436

internal: don't add self pkg .mi into -i if it's in test-import

---

crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/common.rs

cc https://github.com/moonbitlang/moon/pull/478

disable fmt block style by default

---

crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/moon_install_bin.in/user.in/main/moon.pkg.json
crates/moon/tests/test_cases/moon_install_bin.in/user.in/moon.mod.json
crates/mooncake/src/pkg/install.rs
crates/moonutil/src/dependency.rs

- remove alias in bin-deps[bin_pkg]
- change bin install location to bin_mod_path(use "node .mooncakes/hackwaly/moonyacc/moonyacc.js" in pre-build command)
cc @hackwaly

internal: tweak install bin

---

crates/moonbuild/src/gen/gen_check.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonbuild/src/gen/util.rs

close https://github.com/moonbitlang/moon/issues/507

fix: duplicate alias detection when pkg in the same level with mod

---

Cargo.lock
Cargo.toml

fs4 0.10.0 has been yanked
https://crates.io/crates/fs4/0.10.0

update fs4 to version 0.12.0

---

crates/moonbuild/src/new.rs

- Add .DS_Store to generated gitignore

feat: moon new create gitignore add .DS_Store

---

crates/moonrun/src/main.rs
crates/moonrun/tests/test.rs
crates/moonrun/tests/test_cases/test_read_bytes.in/.gitignore
crates/moonrun/tests/test_cases/test_read_bytes.in/README.md
crates/moonrun/tests/test_cases/test_read_bytes.in/main/main.mbt
crates/moonrun/tests/test_cases/test_read_bytes.in/main/moon.pkg.json
crates/moonrun/tests/test_cases/test_read_bytes.in/moon.mod.json

support read_bytes_from_stdin ffi

support read_bytes_from_stdin ffi

---

Cargo.lock
crates/moonbuild/Cargo.toml
crates/moonbuild/src/build.rs
crates/moonbuild/src/runtest.rs

internal: use node.cmd for windows

---

crates/moonutil/src/common.rs

- `node_modules` was excluded from the list of modules scanned

Ignore node modules when scanning project for changes

---

.github/workflows/ci.yml

ci: no autocrlf

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/expect.rs

- https://github.com/moonbitlang/core/pull/1676 
- https://github.com/moonbitlang/core/pull/1691
- ____

support base16 encoding in inspect

---

Cargo.lock
Cargo.toml
crates/moonbuild/Cargo.toml
crates/moonbuild/src/expect.rs

support base64 for inspect

---

crates/moonutil/src/scan.rs

fix unknown target in conditional compilation

---

crates/moon/tests/test_cases/mod.rs

fix a test on Windows

---

crates/moonrun/src/fs_api_temp.rs

feat: allow to get current working directory

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonbuild/src/runtest.rs
crates/mooncake/src/pkg/install.rs
crates/moonutil/src/common.rs
crates/moonutil/src/moon_dir.rs

`moon` will use `tcc` on Linux/macOS platform when run mode is test and the debug flag is set. It will greatly improve the speed of tests that produce large c code.

Use `tcc` when in test mode and debug build

---

crates/moon/src/cli/pre_build.rs
crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/module.rs

Fix https://github.com/moonbitlang/moon/issues/678
- ____

short circuit pre build

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/upgrade.rs

moon upgrade will use the installation script described in https://www.moonbitlang.com/download/ 
- ____

use installation script in moon upgrade

---

crates/moonbuild/src/upgrade.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

support upgrade --dev

---

licenserc.toml
xtask/README.md
xtask/src/sync_docs.rs

add xtask sync-docs to sync commands docs to moonbit-docs

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/native_backend_tcc_run.in/lib/hello.mbt
crates/moon/tests/test_cases/native_backend_tcc_run.in/lib/moon.pkg.json
crates/moon/tests/test_cases/native_backend_tcc_run.in/main/main.mbt
crates/moon/tests/test_cases/native_backend_tcc_run.in/main/moon.pkg.json
crates/moon/tests/test_cases/native_backend_tcc_run.in/moon.mod.json
crates/moon/tests/test_cases/native_stub.in/native_1.in/lib/stub2.c
crates/moon/tests/test_cases/native_stub.in/native_2.in/libb/stub.c
crates/moon/tests/test_cases/native_stub.in/native_3.in/libbb/stub.c
crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonbuild/src/runtest.rs
crates/mooncake/src/pkg/install.rs
crates/moonutil/src/common.rs
crates/moonutil/src/compiler_flags.rs

- In #695, we only use `tcc -run` if no stub is presented. Now we allow it.

Allow to test with `tcc -run` when stubs exist

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonutil/src/compiler_flags.rs

Use the stub-cc provided by users anyway

---

crates/moon/src/cli/run.rs
crates/moon/tests/test_cases/mod.rs

can't use tcc since here need runtime.c

fix run single mbt on native backend

---

crates/moon/tests/mod.rs
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/moon_info_001.in/moon.test
crates/moon/tests/test_cases/moon_info_002.in/moon.test
crates/moonutil/src/compiler_flags.rs

Allow to override CC for debugging

---

crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/compiler_flags.rs

Add MOON_AR env

---

crates/mooncake/src/registry/online.rs

fix: preserve file permissions

---

crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/common.rs

feat: support ignore postadd

---

crates/moonbuild/template/test_driver/no_args_driver_template_native.mbt
crates/moonbuild/template/test_driver/wasm_args.mbt
crates/moonbuild/template/test_driver/with_args_driver_template_native.mbt

refactor(test_driver): avoid using Char::from_int

---

crates/moonrun/src/main.rs
crates/moonrun/src/sys_api.rs
crates/moonrun/tests/test.rs

Fix CLI arg passing to moonbit programs

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/expect.rs

Update escape sequence format

---

crates/moonbuild/template/test_driver/no_args_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_driver_template_native.mbt

Avoid using index to get string element.

update test driver

---

crates/moon/src/cli/check.rs
crates/moon/src/cli/test.rs
crates/moonbuild/src/watch.rs
crates/moonutil/src/scan.rs

fix moon check --watch no update mbt.md

---

crates/moonutil/src/doc_test.rs

https://github.com/rust-lang/rust/issues/51775

fix write patch json don't sync to disk in time

---

crates/moon/tests/test_cases/virtual_pkg/virtual/deep/lib/lib.mbti
crates/moon/tests/test_cases/virtual_pkg/virtual/deep/lib/moon.pkg.json
crates/moon/tests/test_cases/virtual_pkg/virtual/hello.mbti
crates/moon/tests/test_cases/virtual_pkg/virtual/moon.pkg.json
crates/moonutil/src/scan.rs

When handling the deep nested virtual package, the relative path is misused.
- ____

fix: deep virtual package

---

crates/moonutil/src/common.rs

fix: `set_native_backend_link_flags` didn't consider `RunMode::Bench`

---

crates/moon/src/cli/run.rs

close https://github.com/moonbitlang/moon/issues/847

fix: moon run single mbt should set -llvm-target for msvc

---

crates/moon/src/cli/check.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/all_kind_test.in/lib/hello.mbt
crates/moon/tests/test_cases/all_kind_test.in/lib/hello_test.mbt
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/expect.rs
crates/moonbuild/src/runtest.rs
crates/moonutil/src/common.rs
crates/moonutil/src/doc_test.rs
crates/moonutil/src/render.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

internal: make doc test file name be the original file name

---

crates/moon/src/cli/generate_test_driver.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/template/test_driver/no_args_driver_template.mbt
crates/moonbuild/template/test_driver/no_args_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_bench_driver_template.mbt
crates/moonbuild/template/test_driver/with_args_bench_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_driver_template.mbt
crates/moonbuild/template/test_driver/with_args_driver_template_native.mbt

Separate bench drivers from normal test drivers

---

crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonutil/src/common.rs

close https://github.com/moonbitlang/moon/issues/834

feat: support native-stub for llvm backend

---

crates/moonbuild/template/test_driver/no_args_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_bench_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_driver_template_native.mbt

chore: deprecate String::substring

---

crates/moon/src/cli/coverage.rs
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/moon_coverage.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

feat(cli/coverage): add `moon coverage analyze` subcommand for one-stop analysis

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs

- **Revert "fix: Revert to OG Ninja behavior to reduce tasks running"**

Fix markdown parsing regression (2/2)

---

crates/moon/tests/test_cases/moon_commands/mod.rs
crates/moonutil/src/cli.rs
crates/moonutil/src/features.rs
crates/moonutil/src/lib.rs

Add support for unstable features with FeatureGate implementation

---

crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mbti/mod.rs
crates/moon/tests/test_cases/moon_info_001.in/moon.test
crates/moon/tests/test_cases/moon_info_002.in/moon.test
crates/moonutil/build.rs

fix(cli/test): eliminate `.unwrap()` calls in `run_test()`

---

crates/moon/src/cli.rs
crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/diag_loc_map.in/parser.mbt
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/moon_coverage.rs
crates/moonbuild/src/entry.rs
crates/mooncake/src/pkg/install.rs
crates/moonutil/src/common.rs
crates/moonutil/src/render.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

feat(build): add `--render_no_loc` diagnostic level control

---

crates/moon/src/cli/coverage.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/moon_coverage.rs

fix(cli/coverage/analyze): use quiet mode when running `moon test`

---

crates/moonutil/src/common.rs

Closes #935. Verified locally.
- ____

fix(common): recognize "warning" as a possible `DiagnosticLevel`

---

crates/moon/src/cli/new.rs
crates/moon/tests/test_cases/moon_new/mod.rs
crates/moonbuild/src/new.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

- Simplify the `moon new` cli
- Use file stem as default package name

refactor: modify-template-name

---

crates/moon/src/cli/version.rs
crates/moonutil/src/common.rs

feat(cli/version): run `moon-pilot --version` in `moon version --all`

---

crates/moon/tests/test_cases/mod.rs
crates/moonutil/build.rs

chore: update error code dependency

---

crates/moon/tests/test_cases/moon_new/mod.rs
crates/moonbuild/src/new.rs
crates/moonbuild/template/moon_new_template/.githooks/README.md
crates/moonbuild/template/moon_new_template/.githooks/pre-commit
crates/moonbuild/template/moon_new_template/Agents.md

feat: adjust template

---

crates/moon/src/cli/check.rs

fix(rr): wrong param order of dirs

---

Cargo.lock
Cargo.toml
crates/moon/Cargo.toml
crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/src/main.rs
crates/moon/src/rr_build/dry_run.rs
crates/moon/src/rr_build/mod.rs
crates/moon/src/run/mod.rs
crates/moon/src/run/runtest.rs
crates/moon/src/run/runtest/filter.rs
crates/moon/src/run/runtest/promotion.rs
crates/moonbuild-rupes-recta/src/build_lower/context.rs
crates/moonbuild-rupes-recta/src/build_lower/mod.rs
crates/moonbuild-rupes-recta/src/compile/mod.rs
crates/moonbuild-rupes-recta/src/cond_comp.rs
crates/moonbuild-rupes-recta/src/lib.rs
crates/moonbuild-rupes-recta/src/model.rs
crates/moonbuild-rupes-recta/src/pkg_name.rs
crates/moonbuild/src/gen/gen_runtest.rs

This PR implements full `moon test --update` support. This is a relative large refactor (1000+ LoC) that changes `moon test` works under the hood. You might want to just check the new impl without the old one.
The logic is as following (you can also find it in `moon::run::runtest`):
1. Build test executable (using [`crate::rr_build`])
2. Run tests using [`run_tests`]
3. Interpret and print the test results using [`ReplacableTestResults::print_result`]
Currently, snapshot promotion of tests require rerunning the test suite
after the values are promoted. The workflow is as follows:
1. Build test executable as usual
2. Run first test pass as usual
3. After the initial test results are generated, pass it to the following:
4. Loop with the result of the last test run, with capped iteration …

[Rupes Recta] Implement `moon test --update`

---

crates/moon/tests/test_cases/fmt/lib/test.mbt.md
crates/moon/tests/test_cases/fmt/mod.rs
crates/moonbuild-rupes-recta/src/fmt.rs
crates/moonbuild/src/fmt.rs

feat: Add support for moonfmt markdown for both legacy and rr

---

crates/moon/tests/test_cases/fmt/mod.rs

fix: Update `moonfmt` behavior from `moonc` repo

---

crates/moon/tests/test_cases/mod.rs

test: Promote core changes

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/src/rr_build/mod.rs
crates/moonbuild-rupes-recta/src/build_lower/compiler/build_interface.rs
crates/moonbuild-rupes-recta/src/build_lower/compiler/mod.rs
crates/moonbuild-rupes-recta/src/build_lower/context.rs
crates/moonbuild-rupes-recta/src/build_lower/lower_aux.rs
crates/moonbuild-rupes-recta/src/build_lower/lower_build.rs
crates/moonbuild-rupes-recta/src/build_plan/builders.rs
crates/moonbuild-rupes-recta/src/build_plan/constructor.rs
crates/moonbuild-rupes-recta/src/build_plan/mod.rs
crates/moonbuild-rupes-recta/src/discover.rs
crates/moonbuild-rupes-recta/src/intent.rs
crates/moonbuild-rupes-recta/src/lib.rs
crates/moonbuild-rupes-recta/src/model.rs
crates/moonbuild-rupes-recta/src/pkg_solve/model.rs
crates/moonbuild-rupes-recta/src/pkg_solve/solve.rs
crates/moonbuild-rupes-recta/src/util.rs
docs/dev/reference/compiler-cmd-ref.md
docs/dev/reference/virtual-pkg.md

This PR adds virtual package support equivalent to the legacy implementation.
- ____

[Rupes Recta] Add virtual package support
