Cargo.lock
Cargo.toml
crates/moon/Cargo.toml
crates/moon/src/cli.rs
crates/moon/src/cli/shell_completion.rs
crates/moon/src/main.rs
crates/moon/tests/test_cases/mod.rs

adds go-like shell completion for bash/elvish/fish/pwsh/zsh.
```bash
moon shell-completion --shell={SHELL}
```
Generates shell completion script at runtime. By default it reads from `$SHELL` to determine the type of shell.
```bash
moon shell-completion --shell={SHELL}
```
The `shell-completion` subcommand generates shell completion scripts for bash/elvish/fish/powershell/zsh.
Use `moon shell-cimpletion` to output a completion script. By default if `--shell` isn't provided explicitly, `moon` will read from `$SHELL` to determine the correct shell type. Providing any of `{bash,elvish,fish,powershell,zsh}` to `--shell` would override this.
Here's how one may use it w/ Zsh:
Zsh autoloads function from `$FPATH`, we could add `$ZSH/completions` to it, and using
```bash
moon shell-completion …
```

FEAT: Add Shell Completion

---

crates/moonbuild/src/upgrade.rs
crates/moonutil/src/moon_dir.rs

Just a workaround. It is also possible that `$MOON_HOME/bin` and `$MOON_HOME/tmp` are not in the same mount point.

fix: rename does not work across mount point

---

Cargo.lock

`time` < v0.3.36 doesn't compile under Rust 1.80. Bumped dependency versions to fix that.

Bump dependency versions. Fix `time` not compiling in rustc 1.80

---

.github/workflows/ci.yml

move cargo clippy after cargo test to save CI time cc @Young-Flash 
Before
After

ci: move cargo clippy after cargo test

---

crates/moon/tests/mod.rs
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/moon_info_001.in/moon.test
crates/moon/tests/test_cases/moon_info_002.in/moon.test
crates/moon/tests/test_cases/specify_source_dir_001.in/moon.test
crates/moon/tests/test_cases/test_moon_info.in/moon.test
crates/moonbuild/src/entry.rs
crates/moonutil/src/render.rs

- Diagnostics will be printed to stderr instead of stdout 
> In most cases, [Report::eprint](https://docs.rs/ariadne/latest/ariadne/struct.Report.html#method.eprint) is the [‘more correct’](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)) function to use. 
>
> - [`ariadne::Report::print`](https://docs.rs/ariadne/latest/ariadne/struct.Report.html#method.print)

Move diagnostic printing to stderr

---

crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonutil/src/common.rs

this PR tweak the `--build-only` flag for `moon run` and `moon test`, with the flag, `moon` will build all the artifacts without   running them, and give a json which indicates the path of artifacts.
cc @hackwaly

internal: tweak --build-only

---

crates/moon/src/cli/generate_test_driver.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/gen/gen_runtest.rs

generate test driver will make driver for a package, we shouldn only pass `--package` to that subcommand, `--file` & `--index` is unnecessary and cause regenerate.

fix generate test driver

---

.gitignore

This patch adds the project files of the IDE RustRover (directory `.idea`) to the file `.gitignore`.

Add directory '.idea' to '.gitignore'

---

crates/moonbuild/src/entry.rs

When the command `node` is not installed locally and I use the following command to run test about backend `js`. The test fails, but the concrete cause is not printed, which is hard for user to debug.
```
$ cargo test --package moon --test mod test_cases::test_js -- --exact
---- test_cases::test_js stdout ----
thread 'test_cases::test_js' panicked at crates/moon/tests/test_cases/mod.rs:6028:18:
Expected success, was 2
stdout:
Total tests: 3, passed: 0, failed: 3.
```
This patch improves the error message. After this patch, the output of the same command is shown below.
```
$ cargo test --package moon --test mod test_cases::test_js -- --exact
---- test_cases::test_js stdout ----
thread 'test_cases::test_js' panicked at crates/moon/tests/test_cases/mod.rs:6028:18:
Expected success, was 2 …
```

Improve error messages of `moon test`

---

crates/moon/src/cli/build.rs

Currently, when using the command `moon build --trace`, the final buffer can't be flushed to the trace file and the last entry, named `main`, is not printed. This patch fixes it.

Flush and close trace file normally when using `moon build --trace`

---

crates/moon/src/cli/test.rs

When using the command `moon test --trace`, the trace file is closed prematurely. The wrong output is shown below.
```
[
{"pid":0, "name":"main", "ts":0, "tid": 0, "ph":"X", "dur":7517}
]
,{"pid":0, "name":"<skip>", "ts":69065, "tid": 4, "ph":"X", "dur":61929}
// skip other information
```
This patch fixes it and the newly right output is shown below.
```
[
{"pid":0, "name":"<skip>", "ts":69065, "tid": 4, "ph":"X", "dur":61929}
// skip other information
]
```

Avoid closing trace file prematurely when using `moon test --trace`

---

README.md
crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/cli.rs
docs/manual-zh/src/tutorial.md
docs/manual/src/tutorial.md

The code shown below is ineffective and can't generate the `Common options` heading.
```
// ineffective
#[clap(next_display_order(2000), next_help_heading("Common options"))]
```
We can use an assignment instead of the method invocation to fix this issue.
```
// effective 
#[clap(next_help_heading = "Common options")]
```
But when using the assignment, the output is not good(shown below).
```
$ moon help
The build system and package manager for MoonBit.
Usage: moon [OPTIONS] <COMMAND>
Commands:
// skip
Options:
-h, --help  Print help
Common Options:
-C, --directory <SOURCE_DIR>   The source code directory. Defaults to the current directory
--target-dir <TARGET_DIR>  The target directory. Defaults to `source_dir/target`
-q, --quiet                    Suppress output
-v, --verbose …
```

Fix ineffective attribute clap with next_help_heading

---

crates/moon/src/cli/check.rs

Currently, when using the command `moon check --watch --trace`, the final buffer can't be flushed to the trace file and the last entry, named `main`, is not printed. This patch fixes it.

Flush and close trace file normally when using `moon check --watch --trace`

---

crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/common.rs

moon test is different from other modes, this PR only adds hints for test

add test hints

---

crates/moonbuild/src/entry.rs

Currently, when using the command `moon test --trace` to record the test time, the output in `trace.json` is not right. The duration is always `0` (shown below).
```
,{"pid":0, "name":"test", "ts":7753866, "tid": 0, "ph":"X", "dur":0}
,{"pid":0, "name":"test", "ts":7758979, "tid": 0, "ph":"X", "dur":0}
```
It is because the code in [entry.rs](https://github.com/moonbitlang/moon/blob/1caf7785baf1f436f21697f1d5993fb53aa6347e/crates/moonbuild/src/entry.rs#L559..L569) just records the time to construct a `Future` instead of the time to run the test.
This PR relies on https://github.com/moonbitlang/n2/pull/2 and can't be integrated before it. After merging these two PRs, the output should be right (as shown below).
```
,{"pid":0, "name":"test", "ts":9205546, "tid": 0, "ph":"X", "dur":401710} …
```

Trace correct test time

---

README.md
crates/moon/src/cli.rs
crates/moon/src/cli/build_matrix.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/src/cli/tool/format_and_diff.rs
crates/moon/src/cli/version.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/upgrade.rs
crates/moonutil/src/cli.rs
docs/manual-zh/src/tutorial.md
docs/manual/src/tutorial.md

This patch mainly tweaks the help message of the commands and options. Detail lists below:
- Add missed help message of some sub-commands and options
- Adjust the order and heading (group) of some options so that the help message looks more pretty and uniformity
- Capitalize the first letter of the first word
- Tweak some names/words
Thanks for your review.

Tweak the help message and comments

---

crates/moon/src/cli/test.rs
crates/moonbuild/src/entry.rs

Currently, when using the command `moon test`, `moon` will create 16 threads by using the `tokio` library. But these 16 threads will never be used after creating. And these 16 threads become more strange when combining with the argument `--no-parallel`. It is a misuse of the library `tokio`.
This patch, which want to fix the issue, contains the following features:
- When the `--no-parallel` is not provided, run the tests parallelly
- the thread count is equal to the logic cores (not the constant 16)
- spawn the test tasks to the `tokio` runtime scheduler (use the threads `tokio` created to run the test)
- When the `--no-parallel` is provided,  run the tests sequentially
- don't create new thread
- run the test one by one in current thread
Thanks for your review.

Improve parallelism for 'moon test'

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moonutil/src/common.rs

This PR:
1. remove `Default` trait for `MoonbuildOpt`. We need to construct `MoonbuildOpt` carefully without implicit operations.
2. add `raw_target_dir` to `MoonbuildOpt`, which corresponds exactly to the `xxx` in `--target xxx` command.
3. prepare for https://github.com/moonbitlang/moon/pull/294, in `moon generate` all modes share the same state. It's better to record the raw target directory, instead of inferring it by some hacks.
- ____

internal: add raw_target_dir in MoonbuildOpt

---

crates/moon/src/cli/deps.rs
crates/mooncake/src/pkg/add.rs

This patch reduces the duplicated code in `add_cli`, changes the parameters of the method `add_latest` and removes the parameter `_registry_config` of the method `add`. Thanks for your review.

Refactor method 'add_cli' to reduce duplicated code

---

README.md
docs/manual-zh/src/tutorial.md
docs/manual/src/tutorial.md

Tweak readme and docs

---

crates/moon/tests/mod.rs
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/util.rs

simplify test utils,
`get_stdout`: get stdout on success and replace dir, backslash, CRLF, etc.
`get_stderr`: get stderr on success and replace dir, backslash, CRLF, etc.
`get_err_stdout`: get stdout on failure and replace dir, backslash, CRLF, etc.
`get_err_stderr`:  get stdout on failure and replace dir, backslash, CRLF, etc.
cc @Young-Flash 
- ____

internal: refactor test utils

---

crates/moonrun/src/fs_api_temp.rs

`./1.txt`(rust) -> `1.txt`(node)

ffi: align rust_style_path with node_style_path

---

crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/src/fmt.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_bundle.rs
crates/moonbuild/src/gen/gen_check.rs
crates/moonbuild/src/gen/gen_runtest.rs
crates/moonbuild/src/gen/util.rs
crates/moonbuild/src/generate.rs
crates/moonutil/src/common.rs
crates/moonutil/src/module.rs
crates/moonutil/src/scan.rs

internal: refactor package filter

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/moonbuild/template/js_driver.js

- when updating expect test, if rerun test success, we should update the test resut directly and `continue` to process the next test result in the `for` loop
- `TestArgs` should be passing to `js_driver.js` instead of hardcoding into it

fix update expect test

---

crates/moonbuild/src/entry.rs
crates/moonbuild/template/js_driver.js

this PR enable running test artifact without cli args for js backend, so ide could use `node` to run `xx.cjs` directly
cc @hackwaly

fix js test args for debug

---

Cargo.lock
crates/moonbuild/Cargo.toml
crates/moonbuild/src/expect.rs

- ____
- [] No
- increase ~0.2M

feat: support @json.inspect

---

crates/moonrun/src/template/js_glue.js

I would like to remove Instant from the glue code for the following reasons:
- Instant is no binding on the Rust side, instead __moonbit_time_unstable has.
- From a consistency perspective, __moonbit_time_unstable is the one that should be retained.

chore: remove invalid Instant

---

crates/moon/src/cli/doc.rs
crates/moon/tests/test_cases/cond_comp.in/moon.test
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/specify_source_dir_001.in/moon.test
crates/moonbuild/src/entry.rs

packages.json now under `target/$backend/release/check/packages.json`, this PR move packages.json to target/, which could help ide to know backend info directly, and removing the `.moonbit-lsp.json`

move packages.json to target/

---

crates/moon/src/cli.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

`build | check | run | bundle` is already in release mode by default (moonc run in release mode if no debug flag provided), this PR just remove the cli parsing error for --release flag for them

internal: enable --release flag for build | check | run | bundle

---

crates/moon/src/cli.rs
crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs

for `run | build | test` (which need link-core), use `cc -O2` if --release is provided for native backend

internal: use cc -O2 for native --release

---

.github/workflows/test-on-main.yml

ci: add mooncake for test-on-main

---

Cargo.lock
Cargo.toml
crates/moonbuild/src/check/normal.rs
crates/moonutil/src/common.rs

internal: add lock for writing target/packages.json

---

crates/moon/src/cli/fmt.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/fmt.rs
crates/moonutil/src/common.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

cc @Yoorkin 
```
moon fmt                      => moon fmt --block-style=true
moon fmt --block-style        => moon fmt --block-style=true
moon fmt --block-style=true   => moon fmt --block-style=true
moon fmt --block-style=false  => moon fmt --block-style=false
```

Enable block style by default

---

crates/moonrun/src/main.rs
crates/moonrun/src/template/js_glue.js

When running `moonrun -i`, it starts an interactive process. The process reads wasm byte sequence from stdin, executes it, and print the result to stdout.

add moonrun -i

---

crates/moonbuild/src/upgrade.rs

close https://github.com/moonbitlang/moon/issues/550

internal: tweak moon upgrade for new toolchain layout

---

crates/moon/src/cli/info.rs

closes https://github.com/moonbitlang/moonbit-docs/issues/420
- To ensure a consistent line ending between platforms, `moon info` writing is delegated to `mooninfo` which writes in a consistent line ending.

Delegate writing `mbti` files to `mooninfo` instead of capturing stdout

---

.github/workflows/check-merge-commit.yml

Fixes merge queue failures caused by this, e.g. https://github.com/moonbitlang/moon/actions/runs/12926229402/job/36048803053

Skip merge commit checking if not triggered by a PR

---

crates/moon/src/cli.rs
crates/moon/src/cli/build.rs
crates/moon/src/cli/bundle.rs
crates/moon/src/cli/check.rs
crates/moon/src/cli/doc.rs
crates/moon/src/cli/fmt.rs
crates/moon/src/cli/generate_test_driver.rs
crates/moon/src/cli/info.rs
crates/moon/src/cli/run.rs
crates/moon/src/cli/test.rs
crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/entry.rs
crates/mooncake/src/pkg/install.rs
crates/moonutil/src/common.rs
docs/manual-zh/src/commands.md
docs/manual/src/commands.md

- Add `-j<N>` commandline arg to control parallelism
- Add an environment variable `MOON_MAX_PAR_TASKS` to limit the maximum tasks building in parallel

Add option to control max build concurrency

---

crates/moonutil/src/dirs.rs

- Before this PR, moon will only ignore directories at root directory. After this PR, moon will ignore directories at every level.

fix: respect IGNORE_DIRS in non-root dirs

---

_typos.toml
crates/moonbuild/src/gen/gen_build.rs

Generate intermediate compilation products (.obj) in the corresponding target directory; if not specified, they will be generated in the current working directory by default, which may cause `fatal error C1083: Cannot open compiler generated file: 'D:\a\core\core\sorted_map.blackbox_test.obj': Permission denied` (./sorted_map & ./immut/sorted_map)

internal: add -Fo`path` for cl

---

crates/moon/src/cli/pre_build.rs
crates/moon/tests/test_cases/mod.rs
crates/moonutil/src/dirs.rs

pre-build tasks may generate new source files, we need to recreate moon.db to reflect the changes.

update moon.db after pre-build

---

crates/moon/tests/test_cases/mod.rs
crates/moonbuild/src/gen/gen_check.rs

fix `moon check` where can_dirty_on_output flag was set incorrectly

---

crates/moon/tests/test_cases/hello/mod.rs
crates/moonutil/src/common.rs
crates/moonutil/src/scan.rs

- Moon now discovers `.mbt.x` files and add user-invisible prebuild rules to use `moonlex` to compile them to `.mbt` files.

Integrate moonlex & moonyacc

---

crates/moonutil/src/moon_dir.rs

Previously, `MOON_DIRS` does not obey the `MOON_HOME` env var set, but looks for `moonc` in PATH. 
This behavior is problematic if `moonc` is set as a shim or symbolic link, using the already-existing `home()` is a more robust option. For development cases where you need to find the files beside `moonc`, it might be better to just manually link them into `MOON_HOME`.

fix: Obey env var `MOON_HOME` when looking for dirs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Selecting a different issue template automatically adds tags so that no more than one prefix is required
e.g. `[Feature Request]` , `[Bug]`

chore: add metadata in issue template

---

crates/moon/src/cli.rs
crates/moon/tests/test_cases/hello/main/main.mbt
crates/moon/tests/test_cases/hello/mod.rs
crates/moonbuild/src/bench.rs
crates/moonbuild/src/new.rs
crates/moonbuild/template/mod.schema.json
crates/mooncake/src/resolver/mvs.rs
crates/moonutil/src/common.rs
crates/moonutil/src/module.rs
docs/manual-zh/src/source/mod_json_schema.html
docs/manual/src/source/mod_json_schema.html

closes #865 
- A new field `preferred-target` is added to `moon.mod.json`. Setting this field will cause all `moon ____` build commands to use this target as the default target to run, when no other overrides are provided.

Add preferred target configuration for modules

---

crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/run_doc_test.in/src/lib/greet.mbt
crates/moon/tests/test_cases/run_doc_test.in/src/lib/hello.mbt
crates/moonutil/src/doc_test.rs

- don't auto wrap doc test block
- ignore ''' code, just support '''mbt | moonbit
cc @bzy-debug

internal: don't auto wrap doc test block

---

crates/moonbuild/src/gen/util.rs
crates/moonutil/src/scan.rs

- Previously cyclic dependency was printed like `[A, B, C, A]`, now it's `A -> B -> C -> A`
cc @peter-jerry-ye

feat: Print dependency cycle with an arrow when meeting cyclic depedency

---

crates/moonbuild/template/test_driver/no_args_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_bench_driver_template_native.mbt
crates/moonbuild/template/test_driver/with_args_driver_template_native.mbt

Reverts moonbitlang/moon#905
native backend relies on substring; and if we use charcode instead, everything in core will rely on package string

Revert "chore: deprecate String::substring"

---

crates/moon/tests/test_cases/moon_test_single_file.in/111.mbt.md
crates/moon/tests/test_cases/test_moonbitlang_x.in/moon.mod.json

Update `moonbitlang/x` so that tests pass again
- ____

chore: Bump dependency to `moonbitlang/x` to `0.4.29` for tests to pass

---

Cargo.lock
Cargo.toml
crates/moon/src/cli/deps.rs
crates/moonbuild/src/build_script.rs
crates/mooncake/Cargo.toml
crates/mooncake/src/dep_dir.rs
crates/mooncake/src/registry/online.rs
crates/mooncake/src/resolver.rs
crates/mooncake/src/resolver/env.rs
crates/mooncake/src/resolver/mvs.rs
crates/moonutil/Cargo.toml
crates/moonutil/src/mooncakes.rs
crates/moonutil/src/package.rs
crates/moonutil/src/scan.rs

- **refactor: Rename pkgname to unqual in ModuleName for consistency**
- **refactor: Update dependencies to use ArcStr for improved performance and memory efficiency**
- **refactor: Make `ModuleSource` cheaply clonable**
- **refactor: Allow resolved alias to still be optional, and move alias dedup check backwards**
- **refactor: Add reverse mapping and root modules info for module resolver**
- ____

Rollup (1) of misc pre-merge changes for Rupes Recta prototype

---

Cargo.lock
crates/moon/Cargo.toml
crates/moon/src/cli.rs
crates/moon/src/cli/external.rs
crates/moon/src/main.rs

This PR brings `moon` closer to `git` and `cargo`'s behavior WRT external subcommands, that is, `moon <subcmd>` will fall back to calling `moon-{name}` if such a binary is found in `PATH`.
This encourages exploration of tooling ideas without relying on `moon`'s codebase itself while keeping a unified user experience. Famous examples include [`git-branchless`](https://github.com/arxanas/git-branchless), [`cargo-binstall`](https://github.com/cargo-bins/cargo-binstall), [`cargo-chef`](https://github.com/LukeMathWalker/cargo-chef) and [`cargo-zigbuild`](https://github.com/rust-cross/cargo-zigbuild).
See https://doc.rust-lang.org/cargo/reference/external-tools.html#custom-subcommands for more discussion on the rationale of this feature.

feat(moon): support external subcommands

---

crates/moon/tests/test_cases/moon_coverage.rs

Since the `-f=caret` format is currently more stable, this PR changes the snapshot test to use that format to prevent further upstream changes.

test: promote snapshots

---

crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/.gitignore
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/LICENSE
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/README.md
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/moon.mod.json
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/impl/moon.pkg.json
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/impl/p.mbt
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/main/main.mbt
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/main/moon.pkg.json
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/middle/moon.pkg.json
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/middle/p.mbt
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/virtual/moon.pkg.json
crates/moon/tests/test_cases/virtual_pkg_dep/indirect_depend_virtual/src/virtual/pkg.mbti
crates/moon/tests/test_cases/virtual_pkg_dep/mod.rs
crates/moonbuild/src/gen/util.rs

Consider the scenario:
```
virtual --> middle --> main
|                     ^
|                     |
+---------------------+
```
In `moon.pkg.json` of main, it claims an implementation package `impl` is used as the implementation of `virtual`.
Previous behavior will insert `impl.core` to twice for some intricate reasons:
* When it visits `main`, `virtual` is added as a dependency. Because `moon.pkg.json` of `main` says use `impl` for `virtual`, it will add `impl.core` to the worklist.
* When it visits `middle`, `virtual` is added as a dependency. But this time it doesn't know which implementation should be used. So it add `virtual.core` to the worklist.
So the generated `link-core` command will contain a `virtual.core` and a `impl.core`. Before the command is issued, it run another pass …

fix incorrect implementation of virtual package

---

Cargo.lock
crates/moon/tests/test_cases/cond_comp.in/moon.test
crates/moon/tests/test_cases/mod.rs
crates/moon/tests/test_cases/warns/mod.rs
crates/moonbuild/Cargo.toml
crates/moonbuild/src/entry.rs
crates/moonutil/src/render.rs

Upon build process finish, `moon` will report the statistic of warnings & errors
```
Finished. moon: ran 1 task, now up to date (1 warnings, 0 errors)
```
```
Finished. moon: no work to do (1 warnings, 0 errors)
```
```
Failed with 5 warnings, 100 errors.
error: failed to build project
```
If the result has no warning AND no error, the message will not be displayed, like
```
Finished. moon: no work to do
```
- see above

Add build statistics display

---

crates/moon/src/cli/new.rs
crates/moon/tests/test_cases/moon_new/mod.rs
crates/moonbuild/src/new.rs

- The message after `moon new` is changed to show the generated mooncake name
- The warning messages are printed if username is missing

chore: warning for username and print final cakename

---

crates/moonbuild/src/new.rs

- When symbolic creation failed, it will only print error message instead of crash

fix: print warning instead of fail during moon new

---

crates/moon/src/cli/run.rs
crates/moon/src/rr_build/mod.rs
crates/moon/src/run/runtest.rs
crates/moonbuild-rupes-recta/src/build_lower/artifact.rs
crates/moonbuild-rupes-recta/src/build_lower/compiler/mod.rs
crates/moonbuild-rupes-recta/src/build_lower/mod.rs
crates/moonbuild-rupes-recta/src/build_plan/mod.rs
crates/moonbuild-rupes-recta/src/compile/mod.rs
crates/moonbuild-rupes-recta/src/cond_comp.rs
crates/moonbuild-rupes-recta/src/discover.rs
crates/moonbuild-rupes-recta/src/lib.rs
crates/moonbuild-rupes-recta/src/model.rs
crates/moonbuild-rupes-recta/src/pkg_name.rs
crates/moonbuild-rupes-recta/src/special_cases.rs
crates/moonbuild-rupes-recta/src/util.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonutil/src/compiler_flags.rs

This PR adds build system support for native backend, and fixes a couple issues in test execution.
In order to support native backend, a couple new build plan node types need to be added, in particular `BuildRuntimeLibrary` which has no imports. In return, a refactor around the node type was made to make this change easy. Subsequent refactors remove duplicated build metadata, so different nodes can share the same data.
This PR might still contain some issues related to test execution. In particular, the number of tests executed in `core` is not right -- expected 5290 vs executed 4409. Nevertheless, I think it's about the time to merge a milestone of it to trunk. Next up, it might be time to add integration tests.
- ____

[Rupes Recta] Basic native backend support

---

crates/moon/src/cli/generate_test_driver.rs
crates/moonutil/src/common.rs

Fixes #988 
The test driver needs to use a number of standard library types. It uses their fully-qualified names (like `@moonbitlang/core/builtin.Map`) to prevent clashing with local type names. However, the test driver generator explicitly excludes the standard library itself for FQN-ing. This behavior has caused troubles when standard library types shadows builtin types with the same name. See #988 for more info.
This PR reduces the no-FQN behavior to just `@moonbitlang/core/builtin` itself, so that in other standard library packages, types can use the same type name as `builtin`, like `@moonbitlang/core/immut/hashmap.Map`.
I have tried an alternative approach of completely removing the type annotation. However, since test drivers may encounter cases where zero test are included, the …

Reduce blast radius of builtin FQN stripping to `builtin` itself

---

crates/moon/src/run/runtest.rs
crates/moon/src/run/runtest/filter.rs

Test filtering didn't work before, because the algorithm was wrong.
- ____

[Rupes Recta] Fix test filter working issue

---

crates/moon/tests/test_cases/warns/mod.rs
crates/moonbuild-rupes-recta/src/build_lower/compiler/mod.rs
crates/moonbuild/src/gen/gen_build.rs
crates/moonbuild/src/gen/gen_check.rs

Update deny warn list to latest moonc.
This is a temporary solution; we will need to add a "deny all open warnings" option in moonc.
- ____

fix: update deny warn list

---

crates/moon/tests/test_cases/moon_bench/lib/hello_bench.mbt
crates/moon/tests/test_cases/moon_bench/mod.rs

Add test for `moon bench --build-only`, so that we can detect build failure and warnings in the benchmark driver. This PR only tests `--build-only` because the result of actually running `moon bench` is unstable, so testing that part may require some clever post processing on the output.

add test for `moon bench`
